controller:
  services:
    externalIPs: 
      loadBalancerIP: "34.117.180.174"

  metrics:
    port: 10254
    portName: metrics
    enabled: true
    service:
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

    

  
 
      