apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: serv-account
spec:
  refreshInterval: 1m            # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: secrets-store               # name of the SecretStore (or kind specified)
  target:
    name: serv-account  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: secret-access-credentials
    remoteRef:            
      key: serv-account