apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-server
  namespace: argocd
spec:
  project: default
  source:
    path: k8/dev/app/server
    repoURL: https://github.com/applaudo-gcp-tp/ktamariz_finalproject_socialmedia.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app